"""empty message

Revision ID: 1e1e62d5d6d8
Revises: 79ab428b05a6
Create Date: 2022-12-28 22:47:14.246952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e1e62d5d6d8'
down_revision = '79ab428b05a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.REAL(),
    #            type_=sa.Float(precision=2),
    #            existing_nullable=False)
    op.execute("UPDATE items SET description = False")

    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.Float(precision=2),
    #            type_=sa.REAL(),
    #            existing_nullable=False)

    # ### end Alembic commands ###
